name: Build tweak

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: beerpiss/theos-action@v1

      - name: Build package
        run: make package FINALPACKAGE=1

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ReturnToLiveContainer
          path: .theos/packages/*.deb
